### ISSUE TITLE
Search for genus prefers a species result instead

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/ala-name-matching#123]
Two examples so far:

1. "Zonaria" - prefers species "Drosera zonaria": https://bie.ala.org.au/search?sortField=&dir=desc&q=zonaria - https://support.ehelp.edu.au/a/tickets/111209
2. "Solanum" - prefer species "Solanum torvum": https://bie.ala.org.au/search?sortField=score&dir=desc&q=solanum - https://support.ehelp.edu.au/a/tickets/111961

This is particularly an issue for AVH users where there is no easy way to manually search for a genus only when given species search results.

**Comment by charvolant** [comment]
Fixed in AVH by use of namematching webservice rather than BIE to look up names. The BIE still does human-oriented search and prefers species. But that's OK.
