### ISSUE TITLE
404 in some links of the Readme

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-name-matching#136]
These links from the [README](https://github.com/AtlasOfLivingAustralia/ala-name-matching/blob/master/README.md) are broken and should be updated:
- http://nexus.ala.org.au/service/local/repositories/releases/content/au/org/ala/ala-name-matching/3.5/ala-name-matching-distribution-4.0-SNAPSHOT-distribution.zip 
- https://biocache.ala.org.au/archives/nameindexes/20220629 
- and `ala-name-matching-4.0-SNAPSHOT-distribution.zip` links to the `3.5` release.

**Comment by djtfmartin** [comment]
cc @charvolant

**Comment by charvolant** [comment]
Updated in https://github.com/AtlasOfLivingAustralia/ala-name-matching/commit/fcd01bb8ff6a20718fd7e7f085f2fdadb7d904bd
