### ISSUE TITLE
TaxonomyBuilder `OutOfMemoryError` error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-name-matching#162]
Running the merge script results in a `java.lang.OutOfMemoryError: GC overhead limit exceeded` error when attempting to load the [full GBIF taxonomy](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c). I tried increasing the memory allocation for Java from 6G to 10G and this only resulted in processing more records before triggering the same error.

6G - 2,270,000 records
10G - 3,660,000 records

This suggests there is a memory leak. GBIF contains 6,957,236 taxon names so I'd need ~20G to process it.

**Comment by charvolant** [comment]
The current model is in-memory, since it was designed to cope with the < 1m records in the ALA taxonomy. This will require a complete re-architecture. (Not that that's a bad thing.)

**Comment by nickdos** [comment]
Makes sense now I think of it... will close this as we can always throw more memory at it for time being. Not worth a re-architecture I'd think.
