### ISSUE TITLE
Update name parsing library

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-name-matching#23]
We are currently using ecat-common 1.6 which is very old 2012.
Need to upgrade to https://github.com/gbif/name-parser which is more up to date and cut down version of this library.

**Comment by charvolant** [comment]
Changed in https://github.com/AtlasOfLivingAustralia/ala-name-matching/tree/name-match-redesign

**Comment by charvolant** [comment]
Updated ages ago. Just forgot to close this issue
