### ISSUE TITLE
AVH records: scientific name not correctly matched

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-name-matching#5]
E.g. http://avh.ala.org.au/occurrence/4d79e496-7386-4d23-9e24-e1fc522f2296

CANB : Australian National Herbarium : CBG 33404.1

Provided name: `Correa reflexa (Labill.) Vent. hybrid`

Matched to: [`Correa 'Dusky Bells'`](http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:apni.taxon:381040)

**Comment by charvolant** [comment]
Fixed in Fix in https://github.com/AtlasOfLivingAustralia/ala-name-matching/pull/9
