### ISSUE TITLE
Authors Sweet and Sw. are not merged.

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/ala-name-matching#79]
See Solanum torvum Sweet and Solanum torvum Sw.

We currently use the GBIF author comparator, which draws from an internal database of names and abbreviations. Extend this to include local name abbreviations.

**Comment by ansell** [comment]
Per Doug's mention, the code changes were not actually required to fix this particular issue. However, I have reviewed the new code and it looks good to me.
