### ISSUE TITLE
Merge "close enough" authors from different sources.

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/ala-name-matching#81]
For example Alternanthera sessilis with Alternanthera sessilis (L.) DC. coming from the Australian Plant Census (APC) and Alternanthera sessilis (L.) Roem. & Schult. coming from the New Zealand Organism Register (NZOR).

Unless we have multiple authors from the same source, lower-ranked sources should be merged into the more authoritative version, even if they have different authors; the opinion of the higher-ranked source rules.

**Comment by javier-molina** [comment]
https://support.ehelp.edu.au/a/tickets/37181

**Comment by charvolant** [comment]
A simple solution to this causes interesting problems with Carmichaelia cunninghamii. APC has Carmichaelia cunninghamii Raoul ex Lehm. -> Carmichaelia cunninghamii Raoul (excluded). NZOR has Carmichaelia cunninghamii Raoul as a synonym of Carmichaelia australis. The result is a synonym loop. This may be caused by incorrect principal allocation, since Carmichaelia cunninghamii Raoul ex Lehm. is chosen as the principal, as it is not excluded.
