### ISSUE TITLE
Synonym matching over accepted taxon

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/ala-name-matching#83]
Acacia longissima H.L.Wendl. should match the accepted Acacia longissima. Instead it matches to Acacia provincialis via a synonym.

See ://biocache.ala.org.au/occurrences/ecaa8d4e-0cd4-4d7a-a79b-a6ddf7690ef9

**Comment by peri-bolton-abrs** [comment]
_Acacia longissima_ Chopinet is listed as a synonym for _Acacia provincialis_. https://biodiversity.org.au/nsl/services/rest/instance/apni/615832
Note that this is a different concept from _Acacia longissima_ H.L.Wendl.

**Comment by charvolant** [comment]
There seems to be a more general problem where bare Acacia longissima makes its way to Acacia provincialis. Generally, if we just get Acacia longissima without an author, it should go to Acacia longissima H.L.Wendl. -- there's one instance of a supplied name of Acacia longissima H.L.Wendl. going to Acacia provincialis but also 1043 bare Acacia longissima being matched to Acacia provincialis.

**Comment by charvolant** [comment]
This no longer appears to be a problem in the latest 20200214 name index. Added test cases to check for it re-occurring in later releases. See #98
